easyverein:
  host: "easyverein.com"
  path: "/api/stable/"
  token: "<EASYVEREIN-API-TOKEN>"
  options:
    limit: 100 # easyverein provides max limit of 100 members per page
wordpress:
  host: "your-domain.com"
  path: "/wp-json/wp/v2/"
  user: "username"
  pass: "password"
  options:
    per_page: 100 # wordpress provides max limit of 100 users per page
    context: "edit"
