api:
  port: 8080
  token: superSecureToken!
  auth-offset: 60 # offset of auth timestamp in seconds
easyverein:
  host: "easyverein.com"
  path: "/api/stable/"
  token: "<EASYVEREIN-API-TOKEN>"
  options:
    limit: 100 # easyverein provides max limit of 100 members per page
wordpress:
  host: "your-domain.com"
  path: "/wp-json/wp/v2/"
  user: "username"
  pass: "password"
  default-password: "superSecurePW" # default password if password createion (date of birth) failed
  options:
    per_page: 100 # wordpress provides max limit of 100 users per page
    context: "edit"
  blacklist: # list of usernames that will be skipped in user synchronisation
    - max.mustemann
    - franz.joseph.strauss
